### ISSUE TITLE
Does it work with scratch files as well ?

### ISSUE THREAD

**Issue by 573** [stepanvalyavskiy/Decorate.me#4]
Using the following file AppData\Roaming\JetBrains\IdeaIC2020.1\scratches\scratch_20.java

```
class Scratch {
    public static void main(String[] args) {
    }

    // See https://github.com/stepanvalyavskiy/Decorate.me#in-action for How-to. Spoiler: CTRL-SHIFT-SPACE
    void run() {
        // start with new Original(). // Smart-Cmpl
        new Original();
//        new YetAnotherDecorator(new Decorator(new Original()));
    }

    interface Ifc {}

    class Original implements Ifc {}

    class Decorator implements Ifc {
        Decorator(Ifc original){}
    }

    class YetAnotherDecorator implements Ifc {
        YetAnotherDecorator(Ifc original){}
    }
}
```

there were no suggestions in the completions list. I guess it is due to inner classes not (yet) compiled when unused ?

**Comment by stepanvalyavskiy** [comment]
It works with scratches files but not in that way.
It will suggest you Decorators, if they belongs to current project or its dependencies. 
Scratches files do not belong to any project.

So if you want to have an example in your scratch file and let it work in any project, you should take some classes that exist in any project. Something from _java.lang.*_ fits

Here are 2 examples:
```
    void ex1() {
        // start with new String(). // Smart-Cmpl // Search for StringBuilder
        new String();
        // new StringBuilder(new String());
    }

    void ex2() {
        // start with new ByteArrayInputStream(new byte[0]). // Smart-Cmpl // Search for PushbackInputStream
        new ByteArrayInputStream(new byte[0]);
        // new PushbackInputStream(new ByteArrayInputStream(new byte[0]));
    }
```
Why so:

To find Decorators I use 
```
com.intellij.psi.search.searches.ClassInheritorsSearch#search(com.intellij.psi.PsiClass, com.intellij.psi.search.SearchScope, boolean)
 
```
It can search in some scopes related to your project. Scratches files do not belong to any project. But if I get project from scratch file, it returns current opened project. So the plugin try to search Decorators in that project and can't access scratches files.

I have tried to include scratches  files in the search scope but have not found a solution yet. 
**I think it's impossible due idea implementation.**

**Comment by 573** [comment]
@stepanvalyavskiy thanks! Totally works for me then!
