### ISSUE TITLE
no releases are published

### ISSUE THREAD

**Issue by yegor256** [stepanvalyavskiy/Decorate.me#8]
Currently, releases are not published in the GitHub repo. Would be great, if they get there automatically, when you deploy to JetBrains.

**Comment by stepanvalyavskiy** [comment]
Hello @yegor256,
Thank you for your suggestion, I've automated publish workflow.
When new 'v*' tag is created, releases are published simultaneously to GitHub and JetBrains Marketplace automatically via GitHub Actions.
